version: "3.9"
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data

  webserver:
    image: apache/airflow:2.7.2
    restart: always
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: ''
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: 'true'
      AIRFLOW__WEBSERVER__SECRET_KEY: "minha-chave-secreta-123"
      AIRFLOW__LOGGING__REMOTE_LOGGING: "False"
      KAGGLE_CONFIG_DIR: /opt/airflow/chaves
      _PIP_ADDITIONAL_REQUIREMENTS: "-r /opt/airflow/requirements.txt"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./requirements.txt:/opt/airflow/requirements.txt
      - ../scripts:/opt/airflow/scripts
      - ../data:/opt/airflow/data
      - ../chaves:/opt/airflow/chaves
    ports:
      - "8080:8080"
    command: webserver

  scheduler:
    image: apache/airflow:2.7.2
    restart: always
    depends_on:
      - webserver
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__WEBSERVER__SECRET_KEY: "minha-chave-secreta-123"
      AIRFLOW__LOGGING__REMOTE_LOGGING: "False"
      KAGGLE_CONFIG_DIR: /opt/airflow/chaves
      _PIP_ADDITIONAL_REQUIREMENTS: "-r /opt/airflow/requirements.txt"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./requirements.txt:/opt/airflow/requirements.txt
      - ../scripts:/opt/airflow/scripts
      - ../data:/opt/airflow/data
      - ../chaves:/opt/airflow/chaves
    command: scheduler

volumes:
  postgres-db-volume:
